apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  # namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: microk8s-hostpath
