Master:
  InstallPlugins:
    - kubernetes:1.12.6
    - workflow-job:2.24
    - workflow-aggregator:2.5
    - credentials-binding:1.16
    - git:3.9.1
    - google-oauth-plugin:0.6
    - google-source-plugin:0.3
  # Changed by Hadi, to workaround low memory
  #Cpu: "1"
  Cpu: "500m"
  #Memory: "4Gi"
  Memory: "2000Mi"
  # Changed by Hadi, to workaround low memory
  #JavaOpts: "-Xms3500m -Xmx3500m"
  JavaOpts: "-Xms2048m -Xmx2048m"
  ServiceType: ClusterIP
Agent:
  Enabled: true
  resources:
    requests:
      cpu: "500m"
      memory: "2048Mi"
    limits:
      cpu: "1"
      memory: "2048Mi"
Persistence:
  # Changed by Hadi
  #Size: 100Gi
  Size: 30Gi
NetworkPolicy:
  ApiVersion: networking.k8s.io/v1
rbac:
  install: true
  serviceAccountName: cd-jenkins
