Master:
  InstallPlugins:
    - kubernetes:1.12.6
    - workflow-job:2.24
    - workflow-aggregator:2.5
    - credentials-binding:1.16
    - git:3.9.1
    - google-oauth-plugin:0.6
    - google-source-plugin:0.3
  Cpu: "1"
  # Changed by Hadi, to workaround low memory
  #Memory: "3500Mi"
  Memory: "1Gi"
  # Changed by Hadi, to workaround low memory
  #JavaOpts: "-Xms3500m -Xmx3500m"
  JavaOpts: "-Xms1024m -Xmx1024m"
  ServiceType: ClusterIP
Agent:
  Enabled: true
  resources:
    requests:
      cpu: "500m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
Persistence:
  # Changed by Hadi
  #Size: 100Gi
  Size: 30Gi
NetworkPolicy:
  ApiVersion: networking.k8s.io/v1
rbac:
  install: true
  serviceAccountName: cd-jenkins
