apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: repo-nexus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      securityContext:
          fsGroup: 2000
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          resources:
            limits:
              # Change by Hadi, to workaround low memory
              #memory: "3500Mi"
              #cpu: "1"
              memory: "1536Mi"
              cpu: "400m"
            requests:
              # Change by Hadi, to workaround low memory
              #memory: "2800Mi"
              #cpu: "250m"
              memory: "1000Mi"
              cpu: "100m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
          env:
            - name: INSTALL4J_ADD_VM_PARAMS
              # Change by Hadi, to workaround low memory
              #value: "-Xms1200m -Xmx1200m -XX:MaxDirectMemorySize=2g -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs"
              value: "-Xms500m -Xmx500m -XX:MaxDirectMemorySize=1000m -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs"
      volumes:
        - name: nexus-data
          #emptyDir: {}
          persistentVolumeClaim: 
            claimName: nexus-data-pvc
      priorityClassName: high-priority

