apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: repo-nexus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      securityContext:
          fsGroup: 2000
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          resources:
            limits:
              # Change by Hadi, to workaround low memory
              memory: "3500Mi"
              #memory: "768Mi"
              cpu: "900m"
            requests:
              # Change by Hadi, to workaround low memory
              memory: "2Gi"
              #memory: "512Mi"
              cpu: "200m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
          env:
            - name: INSTALL4J_ADD_VM_PARAMS
              # Change by Hadi, to workaround low memory
              value: "-Xms2000m -Xmx2000m -XX:MaxDirectMemorySize=1g -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs"
              #value: "-Xms384m -Xmx384m -XX:MaxDirectMemorySize=256m -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs"
      volumes:
        - name: nexus-data
          #emptyDir: {}
          persistentVolumeClaim: 
            claimName: nexus-data-pvc
